[build]
  functions = "functions/"
  publish = "public/"

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200

[[redirects]]
  from = "/api/kqxs"
  to = "/.netlify/functions/kqxs"
  status = 200

[[redirects]]
  from = "/api/fuel"
  to = "/.netlify/functions/fuel"
  status = 200

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/api/agriculture"
  to = "/.netlify/functions/agriculture"
  status = 200

[[redirects]]
  from = "/api/youtube-search"
  to = "/.netlify/functions/youtube-search"
  status = 200

[[redirects]]
  from = "/api/image-proxy"
  to = "/.netlify/functions/image-proxy"
  status = 200
